#!/usr/bin/env python3
"""Generate RFC 3454 ranges from Python's frozen Unicode 3.2 stringprep tables.

Run from any directory with Python 3 (standard library only). No network access
or third-party package is needed. --check verifies the checked-in output.
"""
import argparse
from pathlib import Path
import stringprep

PROHIBITED = (
    stringprep.in_table_c12, stringprep.in_table_c21, stringprep.in_table_c22,
    stringprep.in_table_c3, stringprep.in_table_c4, stringprep.in_table_c5,
    stringprep.in_table_c6, stringprep.in_table_c7, stringprep.in_table_c8,
    stringprep.in_table_c9,
)
TABLES = {
    "unassigned": ("A.1", stringprep.in_table_a1),
    "mappedToNothing": ("B.1", stringprep.in_table_b1),
    "nonAsciiSpace": ("C.1.2", stringprep.in_table_c12),
    "prohibited": ("C.1.2 and C.2 through C.9", lambda c: any(check(c) for check in PROHIBITED)),
    "randALCat": ("D.1", stringprep.in_table_d1),
    "lCat": ("D.2", stringprep.in_table_d2),
}


def generate():
    assert stringprep.unicodedata.unidata_version == "3.2.0"
    lines = [
        "// Generated by scripts/generate-saslprep-tables.py; do not edit.",
        "// RFC 3454 Unicode 3.2: https://www.rfc-editor.org/rfc/rfc3454",
        "// Inclusive, sorted, non-overlapping [start, end] pairs.",
    ]
    for name, (section, check) in TABLES.items():
        ranges = []
        start = None
        for cp in range(0x110001):
            included = cp < 0x110000 and check(chr(cp))
            if included and start is None:
                start = cp
            elif not included and start is not None:
                ranges.extend((start, cp - 1))
                start = None
        lines.extend(("", f"// RFC 3454 {section}", f"export const {name}: ReadonlyArray<number> = ["))
        for offset in range(0, len(ranges), 12):
            lines.append("  " + ", ".join(f"0x{cp:04x}" for cp in ranges[offset:offset + 12]) + ",")
        lines.append("]")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = Path(__file__).resolve().parent.parent / "packages/native/src/internal/saslprep-tables.ts"
    output = generate()
    if args.check:
        if target.read_text() != output:
            raise SystemExit("SASLprep tables are out of date")
        print("SASLprep tables match Unicode 3.2")
    else:
        target.write_text(output)
