process.roles=broker,controller
node.id=1
controller.quorum.voters=1@localhost:19093
listeners=PLAINTEXT://:19092,CONTROLLER://:19093,TLS://:19094,AUTH://:19095,AUTHTLS://:19096
advertised.listeners=PLAINTEXT://localhost:19092,TLS://localhost:19094,AUTH://localhost:19095,AUTHTLS://localhost:19096
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,TLS:SSL,AUTH:SASL_PLAINTEXT,AUTHTLS:SASL_SSL
inter.broker.listener.name=PLAINTEXT
controller.listener.names=CONTROLLER
log.dirs=/tmp/effect-kafka-benchmark-logs
num.partitions=1
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
group.initial.rebalance.delay.ms=0
ssl.keystore.type=PEM
ssl.keystore.location=/mnt/certs/broker.pem
ssl.truststore.type=PEM
ssl.truststore.location=/mnt/certs/ca.pem
ssl.client.auth=none
sasl.enabled.mechanisms=PLAIN,SCRAM-SHA-256
listener.name.auth.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required user_benchmark="benchmark-secret";
listener.name.auth.scram-sha-256.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required;
listener.name.authtls.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required user_benchmark="benchmark-secret";
listener.name.authtls.scram-sha-256.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required;
